version: '2.2'

volumes:
  postgres_data: {}
  postgres_data_backups: {}

services:
  lk_inventory:
    build:
      context: .
    ports:
      - "5000:5000"

  postgres:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_data_backups:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
#    command: ["postgres", "-c", "log_statement=all"]
    ports:
      - "9432:5432"
