version: '3'

volumes:
  postgres_data: {}
  postgres_data_backups: {}

services:
  lk_inventory:
    build:
      context: .
    depends_on:
      - postgres
    ports:
      - "5001:5001"

  postgres:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_data_backups:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "9435:5432"
