"""added unique to link service to account

Revision ID: a2694d3c54e3
Revises: 90fc82532b44
Create Date: 2023-02-14 09:49:05.535559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2694d3c54e3'
down_revision = '90fc82532b44'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_service_account_uc', 'service_account_link', ['service_id', 'account_id', 'plan_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_service_account_uc', 'service_account_link', type_='unique')
    # ### end Alembic commands ###
